sass:
  sass_dir: _sass
  style: compressed
  implementation: sass-embedded
url: https://bdeshidev.github.io/ 

include:
  - node_modules/
  - /node_modules/.bin/autoprefixer
  - node_modules/.bin/autoprefixer