sass:
  sass_dir: _sass
  style: compressed
  # implementation: sass-embedded
url: https://bdeshidev.github.io/ 
markdown: kramdown
highlighter: rouge
kramdown:
  parse_block_html: true
  input: GFM

include:
  - node_modules/
  - /node_modules/.bin/autoprefixer
  - node_modules/.bin/autoprefixer