# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Fahim Faysal (B-DeshiDev)
title: Indie Game Dev | Game Programmer
email: 
website:

# Social links
twitter_username: B_DeshiDev
github_username:  BDeshiDev

instagram_username: 
linkedin_username: 
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image:
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Fahim Faysal(aka B-DeshiDev) and I'm a game programmer who makes indie games. I am mainly a Unity programmer.
# Projects Section
# projects_title: Projects
  Games I worked on:
    - [Control: Override] (https://b-deshidev.itch.io/input-override)
    - 
# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Aside from programming for games, I also:
   - Play games.
   - Read books.
   - Write for fun.
   - Watch anime.
   - Write code for stuff outside of games.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
