sass:
  sass_dir: _sass
  style: compressed
  # implementation: sass-embedded
url: https://bdeshidev.github.io/ 
kramdown:
  parse_block_html: true
include:
  - node_modules/
  - /node_modules/.bin/autoprefixer
  - node_modules/.bin/autoprefixer